### PR TITLE
You can set default values just with the right key of any nested array.

### PR DESCRIPTION
**Pull request by koprivajakub**

### CODE REVIEW

**Comment by krejcon3** [comment]
you can set undefined key
specify founded bug

what is right key? array: key => value

**Comment by krejcon3** [comment]
public $arrayItems - rename, private but i think that you dont need it as object property
public function checkValue - rename, private

tip: anonymous function

**Comment by koprivajakub** [comment]
ad: <code>public $arrayItems</code> - rename, private but i think that you dont need it as object property
I think I need that because it is set in another function and call by name is not allowed in Nette.

ad: <code>public function checkValue</code> - rename, private
it must be public, because of that callback in array_walk_recursive

But I will rename it for:

``` php
private $nestedKeys = array();
public setNestedKeys($value, $key) {...}
```

Is it fine for you?

**Comment by krejcon3** [comment]
setNestedKeys cannot be public, do it differently

**Comment by koprivajakub** [comment]
how about this:

``` php
...
array_walk_recursive($items, function($value, $key) {
                    $this->nestedKeys[] = $key;            
                }); 
...
```

**Comment by krejcon3** [comment]
its fine... but... u need not use object property nestedKeys

$keys  = array();
array_walk_recursive($items, function($value, $key) use ($keys) {
                              $keys[] = $key;  
                }); 

not work?

**Comment by koprivajakub** [comment]
Got it, check it now.

**Pull request merged**
